inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'app/services/*_report.rb'
    - 'app/services/collection_loader.rb'
    - 'app/services/report.rb'
    - 'app/services/work_loader.rb'
    - 'app/services/hyrax/actor_factory.rb'
    - 'app/services/hyrax/user_stat_importer.rb'
    - 'app/services/hyrax/custom_stat_importer.rb'
    - 'spec/services/hyrax/actor_factory_spec.rb'
    - 'db/**/*'
    - 'lib/tasks/batch.rake'
    - 'script/**/*'
    - 'spec/services/*_report_spec.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/views/sitemaps/index.xml.builder'
    - 'config/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Metrics/LineLength:
  Max: 450

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/classify_concerns_controller.rb'
    - 'app/services/works_report.rb'
    - 'app/forms/hyrax/forms/batch_upload_form.rb'
    - 'spec/support/hyrax/factory_helpers.rb'
    - 'app/indexers/hyrax/file_set_indexer.rb'
    - 'spec/support/hyrax/helpers/factory_helpers.rb'
    - 'app/services/hyrax/actor_factory.rb'
    - 'app/services/hyrax/custom_stat_importer.rb'
    - 'app/jobs/attach_files_to_work_job.rb'
    - 'app/services/collection_metadata_csv_factory.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/presenters/hyrax/collection_presenter.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/hyrax_helper.rb'

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# We define custom methods like `find_by_user_key`,
# `find_by_created_date`, etc
Rails/DynamicFindBy:
  Enabled: false

Rails/Output:
  Exclude:
    - 'app/services/hyrax/custom_stat_importer.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/jobs/user_edit_profile_event_job.rb'

Rails/TimeZone:
  Exclude:
    - 'spec/services/collection_metadata_csv_factory_spec.rb'
    - 'config/initializers/hyrax.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/support/shared/doi_request.rb'
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'
    - 'spec/models/job_io_wrapper_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'    

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/hyrax/admin_spec.rb'
    - 'spec/features/hyrax/batch_create_spec.rb'
    - 'spec/features/hyrax/batch_edit_spec.rb'
    - 'spec/features/hyrax/browse_dashboard_works_spec.rb'
    - 'spec/features/hyrax/browse_catalog_spec.rb'
    - 'spec/features/hyrax/catalog_search_spec.rb'
    - 'spec/features/hyrax/catalog_index_spec.rb'
    - 'spec/features/catalog_index_spec.rb'
    - 'spec/features/collection_export_spec.rb'
    - 'spec/features/concern_show_spec.rb'
    - 'spec/features/hyrax/collection_multi_membership_spec.rb'
    - 'spec/features/hyrax/collection_spec.rb'
    - 'spec/features/hyrax/collection_type_spec.rb'
    - 'spec/features/hyrax/concern_show_spec.rb'
    - 'spec/features/hyrax/contact_form_spec.rb'
    - 'spec/features/hyrax/create_child_work_spec.rb'
    - 'spec/features/hyrax/create_work_spec.rb'
    - 'spec/features/hyrax/create_work_admin_spec.rb'
    - 'spec/features/hyrax/dashboard/all_works.rb'
    - 'spec/features/hyrax/dashboard/collection_spec.rb'
    - 'spec/features/hyrax/dashboard/display_dashboard_spec.rb'
    - 'spec/features/concern_show_spec.rb'
    - 'spec/features/display_admin_dashboard_spec.rb'
    - 'spec/features/hyrax/edit_content_block_admin_spec.rb'
    - 'spec/features/hyrax/edit_work_spec.rb'
    - 'spec/features/hyrax/embargo_spec.rb'
    - 'spec/features/lease_spec.rb'
    - 'spec/features/hyrax/notifications_spec.rb'
    - 'spec/features/hyrax/ownership_transfer_spec.rb'
    - 'spec/features/hyrax/proxy_spec.rb'
    - 'spec/features/hyrax/search_spec.rb'
    - 'spec/features/hyrax/work_show_spec.rb'
    - 'spec/features/hyrax/workflow_state_changes_spec.rb'
    - 'spec/features/hyrax/users_spec.rb'
    - 'spec/features/uc_shibboleth_spec.rb'
    - 'spec/helpers/hyrax_helper_spec.rb'
    - 'spec/services/expiration_service_spec.rb'
    - 'spec/features/create_document_spec.rb'
    - 'spec/features/create_student_work_spec.rb'
    - 'spec/features/create_medium_spec.rb'
    - 'spec/features/create_image_spec.rb'
    - 'spec/features/create_etd_spec.rb'
    - 'spec/features/create_dataset_spec.rb'
    - 'spec/features/create_article_spec.rb'
    - 'spec/features/create_generic_work_spec.rb'
    - 'spec/views/static/help.html.erb_spec.rb'
    - 'spec/controllers/hyrax/file_sets_controller_spec.rb'
    - 'spec/views/_user_util_links.html.erb_spec.rb'
    - 'spec/forms/hyrax/batch_edit_form_spec.rb'
    - 'spec/jobs/batch_create_job_spec.rb'
    - 'spec/controllers/hyrax/batch_uploads_controller_spec.rb'
    - 'spec/controllers/hyrax/generic_works_controller_spec.rb'
    - 'spec/controllers/concerns/scholar/work_controller_behavior_spec.rb'
    - 'spec/features/create_collection_spec.rb'
    - 'spec/features/catalog_facet_spec.rb'
    - 'spec/jobs/proxy_edit_removal_job_spec.rb'
    - 'spec/support/shared/*'
    - 'spec/features/edit_work_spec.rb'
    - 'spec/services/hyrax/actor_factory_spec.rb'
    - 'spec/features/create_document_doi_spec.rb'
    - 'spec/jobs/identifier_delete_job_spec.rb'
    - 'spec/services/hyrax/default_middleware_stack_spec.rb'
    - 'spec/models/work_and_file_index_spec.rb'
    - 'spec/models/file_view_stat_spec.rb'
    - 'spec/jobs/attach_files_to_work_job_spec.rb'
    - 'spec/controllers/callbacks_controller_spec.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'

RSpec/ExpectActual:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/callbacks_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'

RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/features/hyrax/create_child_work_spec.rb'
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/controllers/concerns/scholar/work_controller_behavior_spec.rb'
    - 'spec/views/hyrax/dashboard/collections/_show_actions.html.erb_spec.rb'
    - 'spec/helpers/hyrax_helper_spec.rb'
    - 'spec/views/catalog/_search_form.html.erb_spec.rb'
    - 'spec/views/hyrax/my/collections/index.html.erb_spec.rb'
    - 'spec/views/hyrax/my/_search_form.html.erb_spec.rb'
    - 'spec/views/hyrax/base/_attributes.html.erb_spec.rb'
    - 'spec/support/shared/is_remotely_identifiable_by_doi.rb'
    - 'spec/services/hyrax/actor_factory_spec.rb'
    - 'spec/lib/scholar_spec.rb'
    - 'spec/jobs/identifier_delete_job_spec.rb'
    - 'spec/services/hyrax/default_middleware_stack_spec.rb'
    - 'spec/jobs/attach_files_to_work_job_spec.rb'
    - 'spec/models/collection_spec.rb'
    
RSpec/NamedSubject:
  Exclude:
    - 'spec/indexers/hyrax/collection_indexer_spec.rb'
    - 'spec/indexers/hyrax/file_set_indexer_spec.rb'
    - 'spec/models/job_io_wrapper_spec.rb'
    - 'spec/support/shared/is_remotely_identifiable_by_doi.rb'
    - 'spec/actors/hyrax/actors/mint_doi_actor_spec.rb'
    - 'spec/services/hyrax/actor_factory_spec.rb'
    - 'spec/services/hyrax/default_middleware_stack_spec.rb'
    - 'spec/models/work_and_file_index_spec.rb'
    - 'spec/services/hyrax/custom_stat_importer_spec.rb'
    - 'spec/models/collection_spec.rb'

# This allows us to have the keys in the .env files
Security/Eval:
  Exclude:
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
    - 'app/api/scholar/shared_params.rb'
    - 'app/api/scholar/v1/concern.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'spec/features/collection_export_spec.rb'

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/GuardClause:
  Exclude:
    - 'app/indexers/hyrax/work_indexer.rb'
    - 'lib/active_fedora/fedora.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'lib/active_fedora/fedora.rb'

Style/RedundantFreeze:
  Exclude:
    - 'lib/active_fedora/fedora.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/support/shared/is_remotely_identifiable_by_doi.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/controllers/concerns/hyrax/works_controller_behavior.rb'
    - 'app/indexers/hyrax/file_set_indexer.rb'
    - 'app/indexers/hyrax/work_indexer.rb'
    - 'app/models/ability.rb'
    - 'app/indexers/hyrax/collection_indexer.rb'
    - 'app/services/hyrax/custom_stat_importer.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/ability.rb'
    - 'app/forms/hyrax/forms/batch_upload_form.rb'
    - 'app/api/*'
    - 'app/api/**/*'
    - 'spec/api/*'
    - 'app/helpers/api_helper.rb'

Lint/HandleExceptions:
  Exclude:
    - 'app/controllers/concerns/scholar/works_controller_behavior.rb'
    - 'spec/features/doi_validation_spec.rb'

RSpec/SubjectStub:
  Enabled: false    

Lint/RescueException:
  Exclude:
    - 'app/services/hyrax/custom_stat_importer.rb'
    
Rails/OutputSafety:
  Exclude:
    - 'app/helpers/hyrax_helper.rb'
    - 'app/renderers/hyrax/renderers/attribute_renderer.rb'
