inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'app/controllers/catalog_controller.rb'
    - 'app/views/sitemaps/index.xml.builder'
    - 'config/**/*'
    - 'config/routes.rb'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/models/ability.rb'

Metrics/LineLength:
  Max: 400

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/classify_concerns_controller.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/presenters/hyrax/collection_presenter.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/hyrax_helper.rb'

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# We define custom methods like `find_by_user_key`,
# `find_by_created_date`, etc
Rails/DynamicFindBy:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/jobs/user_edit_profile_event_job.rb'

Rails/TimeZone:
  Exclude:
    - 'spec/services/collection_metadata_csv_factory_spec.rb'

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/views/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/admin_spec.rb'
    - 'spec/features/batch_create_spec.rb'
    - 'spec/features/batch_edit_spec.rb'
    - 'spec/features/browse_dashboard_works_spec.rb'
    - 'spec/features/browse_catalog_spec.rb'
    - 'spec/features/catalog_search_spec.rb'
    - 'spec/features/catalog_facet_spec.rb'
    - 'spec/features/collection_export_spec.rb'
    - 'spec/features/collection_multi_membership_spec.rb'
    - 'spec/features/collection_spec.rb'
    - 'spec/features/collection_type_spec.rb'
    - 'spec/features/contact_form_spec.rb'
    - 'spec/features/create_child_work_spec.rb'
    - 'spec/features/create_work_spec.rb'
    - 'spec/features/create_work_admin_spec.rb'
    - 'spec/features/dashboard/all_works.rb'
    - 'spec/features/dashboard/collection_spec.rb'
    - 'spec/features/dashboard/display_dashboard_spec.rb'
    - 'spec/features/display_admin_dashboard_spec.rb'
    - 'spec/features/edit_content_block_admin_spec.rb'
    - 'spec/features/edit_work_spec.rb'
    - 'spec/features/embargo_spec.rb'
    - 'spec/features/lease_spec.rb'
    - 'spec/features/notifications_spec.rb'
    - 'spec/features/ownership_transfer_spec.rb'
    - 'spec/features/proxy_spec.rb'
    - 'spec/features/search_spec.rb'
    - 'spec/features/work_show_spec.rb'
    - 'spec/features/workflow_state_changes_spec.rb'
    - 'spec/features/users_spec.rb'
    - 'spec/features/uc_shibboleth_spec.rb'
    - 'spec/helpers/hyrax_helper_spec.rb'
    - 'spec/services/expiration_service_spec.rb'
    - 'spec/features/create_document_spec.rb'
    - 'spec/features/create_student_work_spec.rb'
    - 'spec/features/create_medium_spec.rb'
    - 'spec/features/create_image_spec.rb'
    - 'spec/features/create_etd_spec.rb'
    - 'spec/features/create_dataset_spec.rb'
    - 'spec/features/create_article_spec.rb'
    - 'spec/views/static/help.html.erb_spec.rb'
    - 'spec/controllers/hyrax/file_sets_controller_spec.rb'

RSpec/ExpectActual:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/callbacks_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

# # By default RSpec/MessageSpies has the following:
# #   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# # The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/features/create_child_work_spec.rb'
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/views/hyrax/dashboard/collections/_show_actions.html.erb_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'spec/features/collection_export_spec.rb'

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'app/models/ability.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/models/ability.rb'
