require: rubocop-rspec


AllCops:
  TargetRubyVersion: 2.1
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/test_app_templates/**/*'
    - 'vendor/**/*'
    - 'lib/hyrax/specs/**/*'
    - 'spec/views/hyrax/dashboard/collections/*'

Bundler/DuplicatedGem:  # This doesn't work with engine_cart
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Lint/ImplicitStringConcatenation:
  Exclude:
    - 'lib/generators/hyrax/**/*'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  ExcludedMethods: ['included']
  Exclude:
    - 'hyrax.gemspec'
    - 'lib/tasks/*.rake'
    - 'spec/**/*.rb'
    - 'app/controllers/catalog_controller.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/devise.rb'
    - 'config/routes.rb'
    - 'app/views/sitemaps/index.xml.builder'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Max: 13
  Exclude:
    - 'app/helpers/hyrax/hyrax_helper_behavior.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/hyrax/hyrax_helper_behavior.rb'

Naming/FileName: # https://github.com/bbatsov/rubocop/issues/2973
  Exclude:
    - 'Gemfile'

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'config/initializers/devise.rb'


Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Style/DoubleNegation:
  Exclude:
    - 'spec/features/collection_export_spec.rb'

Style/MethodMissing:
  Exclude:

Style/NumericPredicate:
  Exclude:

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ZeroLengthPredicate:
  Exclude:

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
    - 'app/jobs/user_edit_profile_event_job.rb'

Rails/ApplicationJob:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

# We define custom methods like `find_by_user_key`,
# `find_by_created_date`, etc
Rails/DynamicFindBy:
  Enabled: false

Rails/FilePath:
  Exclude:
    - 'spec/abilities/**/*'

Rails/OutputSafety:
  Exclude:

RSpec/AnyInstance:
  Exclude:
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/abilities/**/*'
    - 'spec/conversions/**/*'
    - 'spec/features/**/*'
    - 'spec/inputs/**/*'
    - 'spec/tasks/rake_spec.rb'
    - 'spec/views/**/*'

Rails/TimeZone:
  Exclude:
    - 'spec/services/collection_metadata_csv_factory_spec.rb'

RSpec/ContextWording:
  Enabled: false

# By default RSpec/MessageSpies has the following:
#   Prefer have_received for setting message expectations. Setup form as a spy using allow or instance_spy.
# The default assumes EnforcedStyle is 'have_received'. Most of our specs are 'receive'
RSpec/MessageSpies:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:

RSpec/ExpectActual:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MessageExpectation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/admin_spec.rb'
    - 'spec/features/batch_create_spec.rb'
    - 'spec/features/batch_edit_spec.rb'
    - 'spec/features/browse_dashboard_works_spec.rb'
    - 'spec/features/browse_catalog_spec.rb'
    - 'spec/features/catalog_search_spec.rb'
    - 'spec/features/collection_export_spec.rb'
    - 'spec/features/collection_multi_membership_spec.rb'
    - 'spec/features/collection_spec.rb'
    - 'spec/features/collection_type_spec.rb'
    - 'spec/features/contact_form_spec.rb'
    - 'spec/features/create_child_work_spec.rb'
    - 'spec/features/create_work_spec.rb'
    - 'spec/features/create_work_admin_spec.rb'
    - 'spec/features/dashboard/all_works.rb'
    - 'spec/features/dashboard/collection_spec.rb'
    - 'spec/features/dashboard/display_dashboard_spec.rb'
    - 'spec/features/display_admin_dashboard_spec.rb'
    - 'spec/features/edit_content_block_admin_spec.rb'
    - 'spec/features/edit_work_spec.rb'
    - 'spec/features/embargo_spec.rb'
    - 'spec/features/lease_spec.rb'
    - 'spec/features/notifications_spec.rb'
    - 'spec/features/ownership_transfer_spec.rb'
    - 'spec/features/proxy_spec.rb'
    - 'spec/features/search_spec.rb'
    - 'spec/features/work_show_spec.rb'
    - 'spec/features/workflow_state_changes_spec.rb'
    - 'spec/features/users_spec.rb'
    - 'spec/features/uc_shibboleth_spec.rb'
    - 'spec/helpers/hyrax_helper_spec.rb'
    - 'spec/services/expiration_service_spec.rb'

RSpec/ExpectInHook:
  Exclude:
    - 'spec/features/ownership_transfer_spec.rb'

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/features/create_child_work_spec.rb'
    - 'spec/controllers/hyrax/contact_form_controller_spec.rb'

RSpec/InstanceVariable:
  Exclude:
    - 'spec/controllers/callbacks_controller_spec.rb'
    - 'spec/controllers/collection_exports_controller_spec.rb'
