<%
  socket = [
  ENV["BOXEN_MYSQL_SOCKET"],
  "/var/run/mysql5/mysqld.sock",
  "/tmp/mysql.sock"
  ].detect { |f| f && File.exist?(f) }

  port = ENV["SCHOLAR_DATABASE_PORT"]
%>

mysql_connection: &mysql_connection
<% if socket %>
  host: <%= ENV["SCHOLAR_DATABASE_HOST"] %>
  socket: <%= socket %>
<% else %>
  host: 127.0.0.1
  port: <%= port %>
<% end %>

database_settings: &database_settings
  <<: *mysql_connection
  adapter:   <%= ENV["SCHOLAR_DATABASE_ADAPTER"] %>
  pool:      <%= ENV["SCHOLAR_DATABASE_POOL"] %>
  username:  <%= ENV["SCHOLAR_DATABASE_USERNAME"] %>
  password:  <%= ENV["SCHOLAR_DATABASE_PASSWORD"] %>
  database:  <%= ENV["SCHOLAR_DATABASE_NAME"] %>
  host:      <%= ENV["SCHOLAR_DATABASE_HOST"] %>
  timeout:   <%= ENV["SCHOLAR_DATABASE_TIMEOUT"] %>
  encoding:  utf8
  RECONNECT: FALSE

default: &default
  adapter: <%= ENV["SCHOLAR_DATABASE_ADAPTER"] %>
  encoding: utf8
  host: <%= ENV["SCHOLAR_DATABASE_HOST"] %>
  username:  <%= ENV["SCHOLAR_DATABASE_USERNAME"] %>
  password:  <%= ENV["SCHOLAR_DATABASE_PASSWORD"] %>
  pool:      <%= ENV["SCHOLAR_DATABASE_POOL"] %>
  timeout:   <%= ENV["SCHOLAR_DATABASE_TIMEOUT"] %>


development:
  <<: *database_settings
test:
  <<: *database_settings
production:
  <<: *database_settings
