# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include Hyrax::BasicMetadata

  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

end
