# frozen_string_literal: true

# Generated by hyrax:models
class Collection < ActiveFedora::Base
  include ::Hyrax::CollectionBehavior
  include ::Hyrax::Collections::Featured
  # You can replace these metadata if they're not suitable
  include Hyrax::BasicMetadata
  self.indexer = Hyrax::CollectionWithBasicMetadataIndexer

  def self.multiple?(field)
    if [:title, :description].include? field.to_sym
      false
    else
      super
    end
  end

  def multiple?(field)
    CollectionForm.multiple? field
  end
end
